### ISSUE TITLE
1. API Challenges

### ISSUE THREAD

**Issue by Psychlosuo** [Psychlosuo/Group-Project-1#3]
WHat DO WE DO GUYS!

**Comment by jasonfleming1** [comment]
found a .csv file of it, must create usable data set

**Comment by jasonfleming1** [comment]
- [ ] found a data set (nathan)
- [ ] create firebase
- [ ] need other APIs that are not just our database

**Comment by jasonfleming1** [comment]
from our data set what can we get from other APIs
- Wikipedia api
- google maps
